### ISSUE TITLE
Use no default column names when names are available

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/rxylib#2]
The plot method uses default plot settings, e.g. `xlab = x [a.u.]"`. 
However, it is possible to extract the column names provided by xylib. The code was implemented by me in commit 704f628, but the method has to be adjusted to use column names of the matrices provided in `data_block`, if there were any.

So, it would be a further enhancement to adjust the print method ...

**Comment by RLumSK** [comment]
Thanks for your work Johannes, plot method extended as suggested.
