### ISSUE TITLE
XSYG - minor issues 

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/rxylib#4]
Two issues, the XSYG-format support is not sufficient. 

1. The minimal example

```{xml}
<?xml version="1.0" encoding="utf-8"?>
<Sample>
  <Sequence>
    <Record>
      <Curve>0,25;212,450;251,60;371,60;0,25;212,450;251,60;371,60</Curve>
    </Record>
  </Sequence>
</Sample>
```

does not fail, but imports nothing. This should not happen. 

2. Correct typo: `lexStuidoVersion` should become `lexStudioVersion` (metadata information)

**Comment by JohannesFriedrich** [comment]
In my opinion your minimal example is not a **XSYG** minimal example. The file _xsyg.cpp_ is designed to export data when the following attributes are set to:
 1) curveType == "measured"
 2) detector != "" 

All these attributes are not available in your example, so nothing is exported.
Until now all my analysed XSYG files fulfil these requirements.

2) changed in commit 4f2756d

**Comment by RLumSK** [comment]
The XSYG-file format definition does not require parameters ... it is XML, everything within the tags itself are metadata ... however, you can set this requirement for the import function, but then it becomes inconsistent.
Btw: I just posted it, because I had some trouble importing curves after modifying the file. The function `Luminescence::read_XSYG2R()` had no problem. Therefore the minimal example.

**Comment by RLumSK** [comment]
Issue closed since it does not really belong to the 'rxylib' package, but the library 'xylib' itself.
